//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giveaways.DataMapping.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giveaways
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giveaways()
        {
            this.GiveawaysAvailable = new HashSet<GiveawaysAvailable>();
            this.RedemptionHistory = new HashSet<RedemptionHistory>();
        }
    
        public int GiveawayId { get; set; }
        public int GiveawayTypeId { get; set; }
        public Nullable<bool> GiveawayStatus { get; set; }
        public string GiveawayName { get; set; }
    
        public virtual GiveawayType GiveawayType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiveawaysAvailable> GiveawaysAvailable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RedemptionHistory> RedemptionHistory { get; set; }
    }
}
