//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giveaways.DataMapping.Mapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiveawaysEntities : DbContext
    {
        public GiveawaysEntities()
            : base("name=GiveawaysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyBranches> CompanyBranches { get; set; }
        public virtual DbSet<CouponCategory> CouponCategory { get; set; }
        public virtual DbSet<Giveaways> Giveaways { get; set; }
        public virtual DbSet<GiveawaysAvailable> GiveawaysAvailable { get; set; }
        public virtual DbSet<GiveawayType> GiveawayType { get; set; }
        public virtual DbSet<LoginDetails> LoginDetails { get; set; }
        public virtual DbSet<RedemptionHistory> RedemptionHistory { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<VideoHistory> VideoHistory { get; set; }
        public virtual DbSet<VideoURLs> VideoURLs { get; set; }
    }
}
