//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiveawaysAvailable
    {
        public string Id { get; set; }
        public int GiveawayId { get; set; }
        public int BranchId { get; set; }
        public int CategoryId { get; set; }
        public int Quantity { get; set; }
    
        public virtual CompanyBranches CompanyBranches { get; set; }
        public virtual CouponCategory CouponCategory { get; set; }
        public virtual Giveaways Giveaways { get; set; }
    }
}
