//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedemptionHistory
    {
        public int Id { get; set; }
        public int GiveawayId { get; set; }
        public string MemberId { get; set; }
    
        public virtual Giveaways Giveaways { get; set; }
        public virtual UserDetails UserDetails { get; set; }
    }
}
