//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoHistory
    {
        public int Id { get; set; }
        public string MemberId { get; set; }
        public int WatchedInZip { get; set; }
        public int VideoId { get; set; }
    
        public virtual UserDetails UserDetails { get; set; }
        public virtual VideoURLs VideoURLs { get; set; }
    }
}
